name: .NET

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Start API
      working-directory: src/Bison.CSVDBService
      run: dotnet run --no-build --urls http://localhost:5229 > api.log 2>&1 &
    - name: Test
      run: dotnet test --no-build --verbosity normal
